import React from 'react'
type Props = {}

const Middle = (props: Props) => {
  return (
    <div className="item flex h-[374px] justify-between bg-[#f2f7fb] px-[160px] pt-[70px]  ">
      <div className=" flex w-[352px] flex-col items-center justify-center  ">
        <img src="/3.svg" className="h-12 w-12" />
        <p className="pt-[36px] font-gal text-lg">Search</p>
        <p className="h-[352px]  pt-[8px] font-gal  text-base text-[#4D4D4D]">
          Simply add a keyword or a term related to your business in the slogan
          maker search box. Wait for the magic to happen.
        </p>
      </div>
      <div className=" flex w-[352px] flex-col items-center justify-center  ">
        <img src="/1.svg" className="h-12 w-12" />
        <p className=" pt-[36px] font-gal text-lg">Select</p>
        <p className="h-[352px]  pt-[8px] font-gal  text-base text-[#4D4D4D]">
          Choose from thousands of options generated by the slogan maker that
          fit your needs.
        </p>
      </div>
      <div className=" flex w-[352px] flex-col items-center justify-center  ">
        <img src="/2.svg" className="h-12 w-12" />
        <p className=" pt-[32px] font-gal text-lg">Stand Out</p>
        <p className="h-[352px]  pt-[8px] font-gal  text-base text-[#4D4D4D]">
          Congrats on your new slogan. It's time to win the world!
        </p>
      </div>

      {/* <img src="/1.svg" />
      <img src="/2.svg" /> */}
    </div>
  )
}

export default Middle
